// Arrays possuem o simbolo do colchetes -> []
// Objetos possuem o simbolo de chaves -> {}

//    Array   
export const times = [
    {
        nome: 'Al-Moçar',
        treinador: {
            nome: 'José da Silva',
            nivel: 5,
        },
        jogadores: [
            {
                posicao: 'goleiro',
                camisa: 1,
                nome: 'Cleberson',
                nivel: 12,
                nacao: 'Bra',
                preco: 2000,
                idade: 35,
            },
            {
                posicao: 'zagueiro',
                camisa: 4,
                nome: 'Wellington Marreta',
                nivel: 12,
                nacao: 'Bra',
                preco: 2000,
                idade: 32,
            },
            {
                posicao: 'zagueiro',
                camisa: 5,
                nome: 'Jairrr Jr',
                nivel: 12,
                nacao: 'Bra',
                preco: 2000,
                idade: 25,
            },
            {
                posicao: 'lateral',
                camisa: 14,
                nome: 'Ezequiel Ramos',
                nivel: 12,
                nacao: 'Bra',
                preco: 2000,
                idade: 24,
            },
            {
                posicao: 'lateral',
                camisa: 19,
                nome: 'Nicolas Pomba',
                nivel: 12,
                nacao: 'Bra',
                preco: 2000,
                idade: 19,
            },
            {
                posicao: 'volante',
                camisa: 6,
                nome: 'Zivou',
                nivel: 18,
                nacao: 'Fra',
                preco: 6000,
                idade: 38,
            },
            {
                posicao: 'meio campo',
                camisa: 10,
                nome: 'Ricardinho',
                nivel: 14,
                nacao: 'Bra',
                preco: 6000,
                idade: 17,
            },
            {
                posicao: 'meio campo',
                camisa: 8,
                nome: 'Matias vargaz',
                nivel: 14,
                nacao: 'Bol',
                preco: 4000,
                idade: 25,
            },
            {
                posicao: 'ponta',
                camisa: 17,
                nome: 'Garnacho',
                nivel: 13,
                nacao: 'Arg',
                preco: 6000,
                idade: 19,
            },
            {
                posicao: 'ponta',
                camisa: 11,
                nome: 'Makelele Giroud',
                nivel: 14,
                nacao: 'Fra',
                preco: 6000,
                idade: 23,
            },
            {
                posicao: 'atacante',
                camisa: 9,
                nome: 'Felix Torres',
                nivel: 17,
                nacao: 'Bra',
                preco: 8000,
                idade: 29,
            },
        ]
    },
    {
        nome: 'Real Samba',
        treinador: {
            nome: 'Pedro Souza',
            nivel: 6,
        },
        jogadores: [
            {
                posicao: 'goleiro',
                camisa: 1,
                nome: 'Diego Samba',
                nivel: 13,
                nacao: 'Bra',
                preco: 2500,
                idade: 32,
            },
            {
                posicao: 'zagueiro',
                camisa: 4,
                nome: 'Ricardo Silva',
                nivel: 11,
                nacao: 'Por',
                preco: 1800,
                idade: 28,
            },
            {
                posicao: 'zagueiro',
                camisa: 5,
                nome: 'Paulo Costa',
                nivel: 11,
                nacao: 'Bra',
                preco: 1900,
                idade: 29,
            },
            {
                posicao: 'lateral',
                camisa: 14,
                nome: 'Lucas Santos',
                nivel: 10,
                nacao: 'Bra',
                preco: 1700,
                idade: 26,
            },
            {
                posicao: 'lateral',
                camisa: 19,
                nome: 'Gabriel Oliveira',
                nivel: 10,
                nacao: 'Bra',
                preco: 1600,
                idade: 24,
            },
            {
                posicao: 'volante',
                camisa: 6,
                nome: 'Fernando Cardoso',
                nivel: 15,
                nacao: 'Por',
                preco: 6500,
                idade: 30,
            },
            {
                posicao: 'meio campo',
                camisa: 10,
                nome: 'Pedro Henrique',
                nivel: 13,
                nacao: 'Bra',
                preco: 6200,
                idade: 27,
            },
            {
                posicao: 'meio campo',
                camisa: 8,
                nome: 'Matias Hernandez',
                nivel: 14,
                nacao: 'Chi',
                preco: 6800,
                idade: 28,
            },
            {
                posicao: 'ponta',
                camisa: 17,
                nome: 'Eduardo Silva',
                nivel: 12,
                nacao: 'Bra',
                preco: 5700,
                idade: 25,
            },
            {
                posicao: 'ponta',
                camisa: 11,
                nome: 'Raul Gonzales',
                nivel: 13,
                nacao: 'Esp',
                preco: 6300,
                idade: 26,
            },
            {
                posicao: 'atacante',
                camisa: 9,
                nome: 'André Santos',
                nivel: 16,
                nacao: 'Bra',
                preco: 8200,
                idade: 31,
            },
        ]
    },
    {
        nome: 'Barcelona Brasileiro',
        treinador: {
            nome: 'Antonio Oliveira',
            nivel: 7,
        },
        jogadores: [
            {
                posicao: 'goleiro',
                camisa: 1,
                nome: 'Marcos Brasil',
                nivel: 14,
                nacao: 'Bra',
                preco: 3000,
                idade: 31,
            },
            {
                posicao: 'zagueiro',
                camisa: 4,
                nome: 'Rodrigo Santos',
                nivel: 12,
                nacao: 'Bra',
                preco: 2200,
                idade: 27,
            },
            {
                posicao: 'zagueiro',
                camisa: 5,
                nome: 'João Oliveira',
                nivel: 12,
                nacao: 'Bra',
                preco: 2300,
                idade: 28,
            },
            {
                posicao: 'lateral',
                camisa: 14,
                nome: 'Luiz Mendes',
                nivel: 11,
                nacao: 'Bra',
                preco: 2100,
                idade: 26,
            },
            {
                posicao: 'lateral',
                camisa: 19,
                nome: 'Rafael Silva',
                nivel: 11,
                nacao: 'Bra',
                preco: 2000,
                idade: 24,
            },
            {
                posicao: 'volante',
                camisa: 6,
                nome: 'Carlos Alberto',
                nivel: 16,
                nacao: 'Bra',
                preco: 7000,
                idade: 29,
            },
            {
                posicao: 'meio campo',
                camisa: 10,
                nome: 'Fernando Oliveira',
                nivel: 15,
                nacao: 'Bra',
                preco: 6500,
                idade: 27,
            },
            {
                posicao: 'meio campo',
                camisa: 8,
                nome: 'Paulo Henrique',
                nivel: 15,
                nacao: 'Bra',
                preco: 6700,
                idade: 28,
            },
            {
                posicao: 'ponta',
                camisa: 17,
                nome: 'Eduardo Lima',
                nivel: 14,
                nacao: 'Bra',
                preco: 6300,
                idade: 25,
            },
            {
                posicao: 'ponta',
                camisa: 11,
                nome: 'Gustavo Silva',
                nivel: 14,
                nacao: 'Bra',
                preco: 6200,
                idade: 26,
            },
            {
                posicao: 'atacante',
                camisa: 9,
                nome: 'José Santos',
                nivel: 18,
                nacao: 'Bra',
                preco: 9000,
                idade: 31,
            },
        ]
    },
    {
        nome: 'Milan Brasileiro',
        treinador: {
            nome: 'Luca Rossi',
            nivel: 8,
        },
        jogadores: [
            {
                posicao: 'goleiro',
                camisa: 1,
                nome: 'Giovanni Rossi',
                nivel: 15,
                nacao: 'Bra',
                preco: 3200,
                idade: 30,
            },
            {
                posicao: 'zagueiro',
                camisa: 4,
                nome: 'Gabriel Rodrigues',
                nivel: 13,
                nacao: 'Bra',
                preco: 2500,
                idade: 28,
            },
            {
                posicao: 'zagueiro',
                camisa: 5,
                nome: 'Lucas Oliveira',
                nivel: 13,
                nacao: 'Bra',
                preco: 2600,
                idade: 29,
            },
            {
                posicao: 'lateral',
                camisa: 14,
                nome: 'Rafael Mendes',
                nivel: 12,
                nacao: 'Bra',
                preco: 2400,
                idade: 26,
            },
            {
                posicao: 'lateral',
                camisa: 19,
                nome: 'Diego Costa',
                nivel: 12,
                nacao: 'Bra',
                preco: 2300,
                idade: 24,
            },
            {
                posicao: 'volante',
                camisa: 6,
                nome: 'Carlos Eduardo',
                nivel: 17,
                nacao: 'Bra',
                preco: 8000,
                idade: 29,
            },
            {
                posicao: 'meio campo',
                camisa: 10,
                nome: 'Fernando Henrique',
                nivel: 16,
                nacao: 'Bra',
                preco: 7500,
                idade: 27,
            },
            {
                posicao: 'meio campo',
                camisa: 8,
                nome: 'Paulo Oliveira',
                nivel: 16,
                nacao: 'Bra',
                preco: 7700,
                idade: 28,
            },
            {
                posicao: 'ponta',
                camisa: 17,
                nome: 'Eduardo Santos',
                nivel: 15,
                nacao: 'Bra',
                preco: 7300,
                idade: 25,
            },
            {
                posicao: 'ponta',
                camisa: 11,
                nome: 'Gustavo Oliveira',
                nivel: 15,
                nacao: 'Bra',
                preco: 7200,
                idade: 26,
            },
            {
                posicao: 'atacante',
                camisa: 9,
                nome: 'José Silva',
                nivel: 19,
                nacao: 'Bra',
                preco: 10000,
                idade: 31,
            },
        ]
    },
    {
        nome: 'Bayern do Rio',
        treinador: {
            nome: 'Klaus Müller',
            nivel: 7,
        },
        jogadores: [
            {
                posicao: 'goleiro',
                camisa: 1,
                nome: 'Manuel Santos',
                nivel: 14,
                nacao: 'Bra',
                preco: 3000,
                idade: 29,
            },
            {
                posicao: 'zagueiro',
                camisa: 4,
                nome: 'Rafael Oliveira',
                nivel: 12,
                nacao: 'Bra',
                preco: 2200,
                idade: 27,
            },
            {
                posicao: 'zagueiro',
                camisa: 5,
                nome: 'João Pedro',
                nivel: 12,
                nacao: 'Bra',
                preco: 2300,
                idade: 28,
            },
            {
                posicao: 'lateral',
                camisa: 14,
                nome: 'Luiz Henrique',
                nivel: 11,
                nacao: 'Bra',
                preco: 2100,
                idade: 26,
            },
            {
                posicao: 'lateral',
                camisa: 19,
                nome: 'Gabriel Silva',
                nivel: 11,
                nacao: 'Bra',
                preco: 2000,
                idade: 24,
            },
            {
                posicao: 'volante',
                camisa: 6,
                nome: 'Carlos Henrique',
                nivel: 16,
                nacao: 'Bra',
                preco: 7000,
                idade: 29,
            },
            {
                posicao: 'meio campo',
                camisa: 10,
                nome: 'Fernando Silva',
                nivel: 15,
                nacao: 'Bra',
                preco: 6500,
                idade: 27,
            },
            {
                posicao: 'meio campo',
                camisa: 8,
                nome: 'Paulo Henrique',
                nivel: 15,
                nacao: 'Bra',
                preco: 6700,
                idade: 28,
            },
            {
                posicao: 'ponta',
                camisa: 17,
                nome: 'Eduardo Lima',
                nivel: 14,
                nacao: 'Bra',
                preco: 6300,
                idade: 25,
            },
            {
                posicao: 'ponta',
                camisa: 11,
                nome: 'Gustavo Silva',
                nivel: 14,
                nacao: 'Bra',
                preco: 6200,
                idade: 26,
            },
            {
                posicao: 'atacante',
                camisa: 9,
                nome: 'José Santos',
                nivel: 18,
                nacao: 'Bra',
                preco: 9000,
                idade: 31,
            },
        ]
    },
    {
        nome: 'Juventus Tropical',
        treinador: {
            nome: 'Mario Costa',
            nivel: 8,
        },
        jogadores: [
            {
                posicao: 'goleiro',
                camisa: 1,
                nome: 'Luigi Bianchi',
                nivel: 16,
                nacao: 'Bra',
                preco: 3500,
                idade: 31,
            },
            {
                posicao: 'zagueiro',
                camisa: 4,
                nome: 'Marco Rodrigues',
                nivel: 14,
                nacao: 'Bra',
                preco: 2800,
                idade: 28,
            },
            {
                posicao: 'zagueiro',
                camisa: 5,
                nome: 'Lucas Oliveira',
                nivel: 14,
                nacao: 'Bra',
                preco: 2900,
                idade: 29,
            },
            {
                posicao: 'lateral',
                camisa: 14,
                nome: 'Rafael Mendes',
                nivel: 13,
                nacao: 'Bra',
                preco: 2700,
                idade: 26,
            },
            {
                posicao: 'lateral',
                camisa: 19,
                nome: 'Diego Costa',
                nivel: 13,
                nacao: 'Bra',
                preco: 2600,
                idade: 24,
            },
            {
                posicao: 'volante',
                camisa: 6,
                nome: 'Carlos Eduardo',
                nivel: 18,
                nacao: 'Bra',
                preco: 9000,
                idade: 29,
            },
            {
                posicao: 'meio campo',
                camisa: 10,
                nome: 'Fernando Henrique',
                nivel: 17,
                nacao: 'Bra',
                preco: 8500,
                idade: 27,
            },
            {
                posicao: 'meio campo',
                camisa: 8,
                nome: 'Paulo Oliveira',
                nivel: 17,
                nacao: 'Bra',
                preco: 8700,
                idade: 28,
            },
            {
                posicao: 'ponta',
                camisa: 17,
                nome: 'Eduardo Santos',
                nivel: 16,
                nacao: 'Bra',
                preco: 8300,
                idade: 25,
            },
            {
                posicao: 'ponta',
                camisa: 11,
                nome: 'Gustavo Oliveira',
                nivel: 16,
                nacao: 'Bra',
                preco: 8200,
                idade: 26,
            },
            {
                posicao: 'atacante',
                camisa: 9,
                nome: 'José Silva',
                nivel: 20,
                nacao: 'Bra',
                preco: 11000,
                idade: 31,
            },
        ]
    }
];

        
    

